# Generated by Django 4.0.3 on 2022-04-11 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('segments', '0002_segments_value_alter_segments_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='segments',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='segments',
            name='type',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='segments',
            name='value',
            field=models.CharField(max_length=50),
        ),
    ]
