name: cloudrun-deploy
on:
  push:
    branches:
      - backend

env:
  SERVICE_NAME: ${{ github.event.repository.name }}
  TRACK: java

jobs:

  build:
    name: Cloud Run Deploy
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@master


      # Setup gcloud CLI
      - uses: google-github-actions/setup-gcloud@v0
        with:
          service_account_email: ${{ secrets.SA_EMAIL }}
          service_account_key: ${{ secrets.GCP_SA_KEY}}
          
      - name: 'Use gcloud CLI'
        run: 'gcloud info'

      - name: Configure project id
        run: |
          gcloud config set project us-gcp-ame-con-116-npd-1
      #Build and Push image
      - name: Build
        run: |-
              docker build -t gcr.io/us-gcp-ame-con-116-npd-1/tmt-be ./Tmarket
              
          # Configure docker to use the gcloud command-line tool as a credential helper
      - run: |
            gcloud auth configure-docker -q
      # Push image to Google Container Registry
      - name: Push
        run: |-
            docker push gcr.io/us-gcp-ame-con-116-npd-1/tmt-be
   
      - name: Deploy
        run: |    
            gcloud run deploy tmt-be --image gcr.io/us-gcp-ame-con-116-npd-1/tmt-be --max-instances 3 --min-instances 2 --memory 1000Mi --platform managed --region us-west2 --allow-unauthenticated  --vpc-connector='hu-conn' --add-cloudsql-instances='huex-new' --set-env-vars=[DBN='tmtdb']
 
